language: python
matrix:
  include:
    - python: "2.6"
      env: TOX_ENV="py26-sqlalchemy{10,11}"
      before_install: pip install "idna<2.8"
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
